FROM nginx

COPY index.html /usr/share/nginx/html
COPY AssignModule.html /usr/share/nginx/html
COPY assignmodule.js /usr/share/nginx/html
COPY CreateModule.html /usr/share/nginx/html
COPY createmodule.js /usr/share/nginx/html
COPY GetModule.html /usr/share/nginx/html
COPY getmodule.js /usr/share/nginx/html
COPY UpdateModule.html /usr/share/nginx/html
COPY updatemodule.js /usr/share/nginx/html